"""empty message

Revision ID: 68ff10587a9f
Revises: e94bcb76a1df
Create Date: 2024-06-05 20:19:10.987621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68ff10587a9f'
down_revision: Union[str, None] = 'e94bcb76a1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transit_gateways', 'vytransit_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('transit_gateways', 'operating_status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('transit_gateways', 'provisioning_status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transit_gateways', 'provisioning_status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('transit_gateways', 'operating_status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('transit_gateways', 'vytransit_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
