"""empty message

Revision ID: 12e9b13b9db7
Revises: 3c55819ffc5b
Create Date: 2024-06-20 08:20:17.963456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "12e9b13b9db7"
down_revision: Union[str, None] = "3c55819ffc5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transit_gateways",
        "id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_column("transit_gateways", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transit_gateways",
        sa.Column("user_id", mysql.VARCHAR(length=255), nullable=True),
    )
    op.alter_column(
        "transit_gateways",
        "id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
