"""empty message

Revision ID: 28580854324a
Revises: ffcc9d803dcd
Create Date: 2024-06-21 20:03:42.254602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "28580854324a"
down_revision: Union[str, None] = "ffcc9d803dcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transit_gateway_vpc_routes",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transit_gateway_vpc_routes", "status")
    # ### end Alembic commands ###
