"""empty message

Revision ID: 8f9d4f05bcab
Revises: ebe284e83942
Create Date: 2024-06-20 22:23:32.124042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "8f9d4f05bcab"
down_revision: Union[str, None] = "ebe284e83942"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transit_gateway_attachments",
        "id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transit_gateway_attachments",
        "id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
