"""empty message

Revision ID: a36fb850c451
Revises: 20f3e0da8369
Create Date: 2024-06-22 00:27:31.409880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a36fb850c451"
down_revision: Union[str, None] = "20f3e0da8369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vpc_transit_gateway_routes",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vpc_transit_gateway_routes", "status")
    # ### end Alembic commands ###
