"""empty message

Revision ID: a96f58339471
Revises: a36fb850c451
Create Date: 2024-06-24 01:41:28.340067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a96f58339471"
down_revision: Union[str, None] = "a36fb850c451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transit_gateway_peering_attachments",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "transit_gateway_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "remote_transit_gateway_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "tunnel_interface_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "remote_tunnel_interface_ip",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("tun_num", sa.Integer(), nullable=True),
        sa.Column("tun_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote_tun_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tun_cidr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["transit_gateway_id"],
            ["transit_gateways.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transit_gateway_peering_attachments")
    # ### end Alembic commands ###
