"""empty message

Revision ID: f4813456b443
Revises: a92483a18be8
Create Date: 2024-06-21 02:03:13.776895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "f4813456b443"
down_revision: Union[str, None] = "a92483a18be8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transit_gateway_vpc_attachments",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vpc_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vpc_net_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "vpc_net_port_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("vpc_cidr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vpc_router_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("transit_gateway_attachments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transit_gateway_attachments",
        sa.Column("id", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("type", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("transit_gateway_id", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("updated_at", mysql.VARCHAR(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["transit_gateway_id"],
            ["transit_gateways.id"],
            name="transit_gateway_attachments_ibfk_1",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb3_general_ci",
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    op.drop_table("transit_gateway_vpc_attachments")
    # ### end Alembic commands ###
