"""empty message

Revision ID: f5c6e6a9b592
Revises: 61437ecee201
Create Date: 2024-06-21 02:47:14.785575

"""

from typing import Sequence, Union
import sqlmodel


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f5c6e6a9b592"
down_revision: Union[str, None] = "61437ecee201"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transit_gateway_vpc_attachments",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_cidr",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_router_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_net_ip",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_net_port_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "transit_gateway_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "vpc_transit_routes",
        "target",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "vpc_transit_routes",
        "destination",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vpc_transit_routes",
        "destination",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "vpc_transit_routes",
        "target",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "transit_gateway_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_net_port_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_net_ip",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_router_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_cidr",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "transit_gateway_vpc_attachments",
        "vpc_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("transit_gateway_vpc_attachments", "status")
    # ### end Alembic commands ###
