"""empty message

Revision ID: f9334b6d13f5
Revises: 86423f35660b
Create Date: 2024-06-25 08:35:14.644612

"""

from typing import Sequence, Union

import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9334b6d13f5"
down_revision: Union[str, None] = "86423f35660b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transit_gateway_peering_attachments",
        sa.Column(
            "remote_region_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transit_gateway_peering_attachments", "remote_region_id")
    # ### end Alembic commands ###
