"""empty message

Revision ID: ffcc9d803dcd
Revises: 6b4092df1ebb
Create Date: 2024-06-21 09:25:20.964486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "ffcc9d803dcd"
down_revision: Union[str, None] = "6b4092df1ebb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transit_gateway_vpc_routes",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("destination", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["target"],
            ["transit_gateway_vpc_attachments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "transit_gateway_vpc_attachments",
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "transit_gateway_vpc_attachments",
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transit_gateway_vpc_attachments", "updated_at")
    op.drop_column("transit_gateway_vpc_attachments", "created_at")
    op.drop_table("transit_gateway_vpc_routes")
    # ### end Alembic commands ###
